namespace REST_API_TEMPLATE.Models
{
    public enum Genre
    {
        Fantasy,
        Adventure,
        Romance,
        Contemporary,
        Dystopian,
        Mystery,
        Horror,
        Thriller,
        Paranormal,
        Historical_fiction,
        Science_Fiction,
        Childrens,
        Memoir,
        Cooking,
        Art,
        Self_help,
        Personal,
        Development,
        Motivational,
        Health,
        History,
        Travel,
        How_to,
        Families_Relationships,
        Humor,
        Biography
    }
}
